package View;

// --- Imports Adicionados ---
import controller.AnalistaDeDadosCtrl;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.AnalistaDeDados;
// --- Fim dos Imports ---

public class FormConsAnalista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConsAnalista.class.getName());

    // --- Nossas Variáveis ---
    private AnalistaDeDadosCtrl controller;
    private DefaultTableModel modTblResultados;
    private static FormConsAnalista cpUnbic;
    // -----------------------

    /**
     * Creates new form FormConsAnalista
     */
    public FormConsAnalista() {
        initComponents();
        
        // --- Nossa Inicialização ---
        this.controller = new AnalistaDeDadosCtrl();
        this.modTblResultados = (DefaultTableModel) tblResultados.getModel();
        // Altera o fechamento para DISPOSE (fecha só esta janela)
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        // Carrega a tabela com todos os dados assim que a tela abre
        carregarTabelaCompleta();
        // --------------------------
    }
    
    /**
     * Método Singleton
     */
    public static FormConsAnalista geraConsAna() {
        if (cpUnbic == null) {
            cpUnbic = new FormConsAnalista();
        }
        return cpUnbic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        cxNomeFiltro = new javax.swing.JTextField();
        cxFerramentaFiltro = new javax.swing.JTextField();
        cxRelatorioFiltro = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btListarTodos = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Qtd. RELATÓRIOS");

        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btListarTodos.setText("LIMPAR");
        btListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarTodosActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Consulta de Analista");

        jLabel2.setText("NOME:");

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "EMAIL", "SALARIO", "FERRAMENTA", "Qtd. RELATORIOS"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        jLabel3.setText("FERRAMENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxFerramentaFiltro))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cxRelatorioFiltro))
                                .addGap(90, 90, 90)
                                .addComponent(btBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btListarTodos))
                            .addComponent(txtTitulo))
                        .addGap(122, 122, 122))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBuscar)
                            .addComponent(btListarTodos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cxFerramentaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cxRelatorioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // 1. Coleta os filtros da tela
        String nome = cxNomeFiltro.getText();
        String ferramenta = cxFerramentaFiltro.getText();
        String qtdRelatorios = cxRelatorioFiltro.getText();
        
        // 2. Chama o controller para buscar com os filtros
        List<AnalistaDeDados> listaFiltrada = controller.buscarPorFiltros(nome, ferramenta, qtdRelatorios);
        
        // 3. Preenche a tabela com os resultados
        preencherTabela(listaFiltrada);        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarTodosActionPerformed
        // 1. Limpa os campos de filtro
        cxNomeFiltro.setText("");
        cxFerramentaFiltro.setText("");
        cxRelatorioFiltro.setText("");
        
        // 2. Carrega a tabela com a lista completa
        carregarTabelaCompleta();
    }//GEN-LAST:event_btListarTodosActionPerformed

    private void carregarTabelaCompleta() {
        // Pede ao controller a lista de todos
        List<AnalistaDeDados> listaCompleta = controller.listaTodos();
        // Manda preencher a tabela
        preencherTabela(listaCompleta);
    }
    
    /**
     * Método auxiliar para preencher a tabela com uma lista de analistas.
     * @param lista A lista (filtrada ou completa) a ser exibida.
     */
    private void preencherTabela(List<AnalistaDeDados> lista) {
        // Limpa a tabela
        modTblResultados.setRowCount(0);
        
        // Itera sobre a lista e adiciona cada analista como uma linha
        for (AnalistaDeDados a : lista) {
            modTblResultados.addRow(new Object[]{
                a.getCpf(),
                a.getNome(),
                a.getEmail(),
                a.getSalario(),
                a.getFerramenta(),      // Coluna específica de Analista
                a.getQtdRelatorios()    // Coluna específica de Analista
            });
        }
    }
        
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConsAnalista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btListarTodos;
    private javax.swing.JTextField cxFerramentaFiltro;
    private javax.swing.JTextField cxNomeFiltro;
    private javax.swing.JTextField cxRelatorioFiltro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
