package View;

//Apache NetBeand IDE 26
//Augusto da Silva de Sá
public class FormPrincipal extends javax.swing.JFrame {

    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloPrincipal = new javax.swing.JLabel();
        btProg = new javax.swing.JButton();
        btAna = new javax.swing.JButton();
        btGer = new javax.swing.JButton();
        btProj = new javax.swing.JButton();
        barMnPrinc = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        itMnCadProg = new javax.swing.JMenuItem();
        itMnCadAnalist = new javax.swing.JMenuItem();
        itMnCadGer = new javax.swing.JMenuItem();
        itMnCadProj = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setLocation(new java.awt.Point(200, 100));

        txtTituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTituloPrincipal.setText("Sistema de Gerenciamento");
        txtTituloPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));

        btProg.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btProg.setText("Gerenciar Programadores");
        btProg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgActionPerformed(evt);
            }
        });

        btAna.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btAna.setText("Gerenciar Analistas de Dados");
        btAna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnaActionPerformed(evt);
            }
        });

        btGer.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btGer.setText("Gerenciar Gerentes");
        btGer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerActionPerformed(evt);
            }
        });

        btProj.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btProj.setText("Gerenciar Projetos");
        btProj.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProjActionPerformed(evt);
            }
        });

        barMnPrinc.setAlignmentX(1.0F);
        barMnPrinc.setAlignmentY(1.0F);

        mnCad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnCad.setText("Formulários de Consulta");
        mnCad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itMnCadProg.setText("Abrir Consulta de Programadores...");
        itMnCadProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadProgActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadProg);

        itMnCadAnalist.setText("Abrir Consulta de Analista de Dados...");
        itMnCadAnalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAnalistActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadAnalist);

        itMnCadGer.setText("Abrir Consulta de Gerente...");
        itMnCadGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadGerActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadGer);

        itMnCadProj.setText("Abrir Consulta de Projeto...");
        itMnCadProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadProjActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadProj);

        barMnPrinc.add(mnCad);

        setJMenuBar(barMnPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btProg, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAna, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGer, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloPrincipal)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAna, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGer, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btProj, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnaActionPerformed
        FormCadAnalista.geraCadAna().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btAnaActionPerformed

    private void btProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgActionPerformed
        FormCadProgramador.geraCadProg().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btProgActionPerformed

    private void btGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerActionPerformed
        FormCadGerente.geraCadGer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btGerActionPerformed

    private void itMnCadProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadProjActionPerformed
        FormConsProjeto.geraConsProj().setVisible(true);
    }//GEN-LAST:event_itMnCadProjActionPerformed

    private void itMnCadGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadGerActionPerformed
        FormConsGerente.geraConsGer().setVisible(true);
    }//GEN-LAST:event_itMnCadGerActionPerformed

    private void itMnCadAnalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAnalistActionPerformed
        FormConsAnalista.geraConsAna().setVisible(true);
    }//GEN-LAST:event_itMnCadAnalistActionPerformed

    private void itMnCadProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadProgActionPerformed
        FormConsProgramador.geraConsProg().setVisible(true);
    }//GEN-LAST:event_itMnCadProgActionPerformed

    private void btProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProjActionPerformed
        FormCadProjeto.geraCadProj().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btProjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMnPrinc;
    private javax.swing.JButton btAna;
    private javax.swing.JButton btGer;
    private javax.swing.JButton btProg;
    private javax.swing.JButton btProj;
    private javax.swing.JMenuItem itMnCadAnalist;
    private javax.swing.JMenuItem itMnCadGer;
    private javax.swing.JMenuItem itMnCadProg;
    private javax.swing.JMenuItem itMnCadProj;
    private javax.swing.JMenu mnCad;
    private javax.swing.JLabel txtTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
