package View;
import model.Programador;
import controller.ProgramadorCtrl; // Já estava aqui, agora será usado em tudo
import Exceptions.NivelSenioridadeInvException;
import java.util.List; // Import necessário para a lista
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadProgramador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadProgramador.class.getName());
    
    private ProgramadorCtrl controller;

    private static FormCadProgramador cpUnbic;

    private FormCadProgramador() {
        initComponents();
        // Instancia o controller uma vez no construtor
        this.controller = new ProgramadorCtrl();
        // Carrega a tabela com os dados do banco assim que o formulário abrir
        listTab();
    }

    public static FormCadProgramador geraCadProg() {
        if (cpUnbic == null) {
            cpUnbic = new FormCadProgramador();
        }
        return cpUnbic;
    }
    //-------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btConsProgCpf = new javax.swing.JButton();
        btAltProgCpf = new javax.swing.JButton();
        btExcProgCpf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProg = new javax.swing.JTable();
        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btInserirProg = new javax.swing.JButton();
        rtSalario = new javax.swing.JLabel();
        cxSalario = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JLabel();
        rtLinguagem = new javax.swing.JLabel();
        cxLinguagem = new javax.swing.JTextField();
        rtNivel = new javax.swing.JLabel();
        cxNivel = new javax.swing.JTextField();
        btGerarDescricao = new javax.swing.JButton();
        cxGerarDescricao = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        rtEmail = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btConsProgCpf.setText("Consultar");
        btConsProgCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsProgCpfActionPerformed(evt);
            }
        });

        btAltProgCpf.setText("Alterar");
        btAltProgCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltProgCpfActionPerformed(evt);
            }
        });

        btExcProgCpf.setText("Excluir");
        btExcProgCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcProgCpfActionPerformed(evt);
            }
        });

        tbProg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "SALARIO", "LINGUAGEM", "NIVEL"
            }
        ));
        tbProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProg);

        rtCpf.setText("CPF:");

        cxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfActionPerformed(evt);
            }
        });

        rtNome.setText("NOME:");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btInserirProg.setText("Inserir");
        btInserirProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirProgActionPerformed(evt);
            }
        });

        rtSalario.setText("SALARIO:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Cadastro de Programador");

        rtLinguagem.setText("LINGUAGEM PRINCIPAL:");

        rtNivel.setText("NÍVEL (Junior, Pleno ou Senior):");

        btGerarDescricao.setText("Gerar Descricao");
        btGerarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDescricaoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Manual de Uso");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        rtEmail.setText("EMAIL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtCpf)
                        .addGap(18, 18, 18)
                        .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSalario)
                                .addGap(18, 18, 18)
                                .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInserirProg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btConsProgCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAltProgCpf)
                                .addGap(18, 18, 18)
                                .addComponent(btExcProgCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtLinguagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxLinguagem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGerarDescricao)
                            .addComponent(cxGerarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(56, 56, 56)
                        .addComponent(btGerarDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxGerarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtEmail)
                            .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtSalario)
                            .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtLinguagem)
                            .addComponent(cxLinguagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNivel)
                            .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInserirProg)
                            .addComponent(btConsProgCpf)
                            .addComponent(btAltProgCpf)
                            .addComponent(btExcProgCpf))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair)))
        );

        cxCpf.getAccessibleContext().setAccessibleName("");
        cxCpf.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsProgCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsProgCpfActionPerformed
        consProgCpf();
    }//GEN-LAST:event_btConsProgCpfActionPerformed

    private void btAltProgCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltProgCpfActionPerformed

        altProgCpf();
        listTab();
    }//GEN-LAST:event_btAltProgCpfActionPerformed

    private void btExcProgCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcProgCpfActionPerformed
        excProgCpf();
        listTab();
    }//GEN-LAST:event_btExcProgCpfActionPerformed

    private void tbProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProgMouseClicked

    }//GEN-LAST:event_tbProgMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirProgActionPerformed
        insProg();
        listTab();
    }//GEN-LAST:event_btInserirProgActionPerformed

    private void cxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfActionPerformed

    private void btGerarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDescricaoActionPerformed
        gerarDescricaoCpf();
    }//GEN-LAST:event_btGerarDescricaoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        exibeManual();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void listTab() {
        DefaultTableModel modTab = (DefaultTableModel) tbProg.getModel();
        modTab.setRowCount(0); // Limpa a tabela

        // Pede ao controller a lista de todos os programadores do banco
        List<Programador> listaProgs = controller.listaTodos();

        for (Programador p : listaProgs) {
            modTab.addRow(new Object[]{
                p.getCpf(),
                p.getNome(),
                p.getSalario(),
                p.getLinguagemP(),
                p.getNivelSen()
            });
        }
    }
    
    public void excProgCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            
            // Pergunta ao usuário para confirmar a exclusão
            int resp = JOptionPane.showConfirmDialog(
                null, 
                "Tem certeza que deseja excluir o programador com CPF " + cpf + "?", 
                "Confirmação de Exclusão", 
                JOptionPane.YES_NO_OPTION
            );
            
            if (resp == JOptionPane.YES_OPTION) {
                // Manda o controller excluir
                controller.exclui(cpf);
                limpar();
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                null,
                "O CPF deve ser um número inteiro!",
                "Erro de Exclusão",
                JOptionPane.ERROR_MESSAGE
            );
            cxCpf.requestFocus();
        }
    }
    
    public void altProgCpf() {
        try {
            Programador p = new Programador();
            p.setCpf(Integer.parseInt(cxCpf.getText()));
            p.setNome(cxNome.getText());
            p.setEmail(cxEmail.getText());
            p.setSalario(Double.parseDouble(cxSalario.getText()));
            p.setLinguagemP(cxLinguagem.getText());
            p.setNivelSen(cxNivel.getText()); // A exceção será tratada abaixo

            // Manda o controller atualizar
            controller.atualiza(p);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "CPF e Salário devem ser números válidos!", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (NivelSenioridadeInvException nsie) {
            JOptionPane.showMessageDialog(null, "Nível de senioridade inválido! Use 'Junior', 'Pleno' ou 'Senior'.", "Dados Inválidos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void consProgCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());

            // Pede ao controller para buscar o programador pelo CPF
            Programador p = controller.buscaPorCpf(cpf);

            if (p != null) {
                // Preenche os campos da tela com os dados encontrados
                cxCpf.setText(String.valueOf(p.getCpf()));
                cxNome.setText(p.getNome());
                cxEmail.setText(p.getEmail());
                cxSalario.setText(String.valueOf(p.getSalario()));
                cxLinguagem.setText(p.getLinguagemP());
                cxNivel.setText(p.getNivelSen());
                
                JOptionPane.showMessageDialog(null, "Programador encontrado!", "Consulta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado no banco de dados.", "Consulta", JOptionPane.WARNING_MESSAGE);
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O CPF deve ser um número inteiro!", "Erro de Consulta", JOptionPane.ERROR_MESSAGE);
            cxCpf.requestFocus();
        }
    }
    
    public void insProg() {
        Programador programador = new Programador();
        try {
            // 1. Coleta os dados da tela
            programador.setCpf(Integer.parseInt(cxCpf.getText()));
            programador.setNome(cxNome.getText());
            programador.setEmail(cxEmail.getText());
            programador.setSalario(Double.parseDouble(cxSalario.getText()));
            programador.setLinguagemP(cxLinguagem.getText());
            programador.setNivelSen(cxNivel.getText()); // Pode lançar NivelSenioridadeInvException

            // 2. Chama o controller da classe para tentar adicionar
            // As mensagens de sucesso (do Controller) ou erro de SQL (do ComandoSQL)
            // serão mostradas por eles.
            boolean sucesso = this.controller.adiciona(programador);

            // 3. Limpa os campos SOMENTE se a operação no banco deu certo
            if (sucesso) {
                limpar();
                listTab(); // Atualiza a tabela após inserção bem-sucedida
            }
            // Se 'sucesso' for false, o ComandoSQL já mostrou o erro (ex: CPF duplicado)
            // e não limpamos os campos para o usuário poder corrigir.

        } catch (NumberFormatException nfe) {
            // Erro de formato nos campos ANTES de ir para o banco
            JOptionPane.showMessageDialog(
                null,
                "CPF e Salário devem ser números válidos!",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        } catch (NivelSenioridadeInvException nsie) {
            // Erro na validação do Nível ANTES de ir para o banco
            JOptionPane.showMessageDialog(
                null,
                "Nível de senioridade inválido! Use 'Junior', 'Pleno' ou 'Senior'.",
                "Dados Inválidos",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        } catch (Exception e) {
            // Captura qualquer outro erro inesperado que possa ocorrer AQUI no formulário
            JOptionPane.showMessageDialog(
                null,
                "Ocorreu um erro inesperado no formulário: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        }
    }
    
    public void gerarDescricaoCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            Programador p = controller.buscaPorCpf(cpf); // Usa o novo método de busca

            if (p != null) {
                cxGerarDescricao.setText(p.gerarDescricaoCargo());
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado!", "Descrição de Cargo", JOptionPane.WARNING_MESSAGE);
                cxGerarDescricao.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Digite apenas números.", "Descrição de Cargo", JOptionPane.ERROR_MESSAGE);
            cxGerarDescricao.setText("");
            cxCpf.requestFocus();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){

           dispose();
       }
    }
    
    public void limpar() {
        cxCpf.setText("");
        cxNome.setText("");
        cxEmail.setText("");
        cxSalario.setText("");
        cxLinguagem.setText("");
        cxNivel.setText("");
        cxGerarDescricao.setText("");
        cxCpf.requestFocus();
    }
    
    private void exibeManual() {
        String manual =
            "=== Manual de Uso do Sistema ===\n\n" +
            "1) Inserir:\n" +
            "   • Digite um CPF novo e os demais dados nas caixas de texto.\n" +
            "   • Clique em Inserir.\n\n" +
            "2) Consultar:\n" +
            "   • Digite um CPF já cadastrado.\n" +
            "   • Clique em Consultar.\n" +
            "   • Todos os dados daquele CPF aparecerão nas caixas de texto.\n\n" +
            "3) Alterar:\n" +
            "   • Digite um CPF já existente.\n" +
            "   • (Opcional) Clique em Consultar para carregar os dados atuais.\n" +
            "   • Edite os campos que desejar.\n" +
            "   • Clique em Alterar para sobrescrever o cadastro.\n\n" +
            "4) Excluir:\n" +
            "   • Digite um CPF existente.\n" +
            "   • Clique em Excluir.\n" +
            "   • Todos os dados desse cadastro serão removidos.\n\n" +
            "Extras:\n" +
            "   • Para calcular bônus ou gerar descrição, insira um CPF cadastrado\n" +
            "     e clique no botão correspondente.";

        JOptionPane.showMessageDialog(
            this,
            manual,
            "Ajuda / Manual do Sistema",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadProgramador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltProgCpf;
    private javax.swing.JButton btConsProgCpf;
    private javax.swing.JButton btExcProgCpf;
    private javax.swing.JButton btGerarDescricao;
    private javax.swing.JButton btInserirProg;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxGerarDescricao;
    private javax.swing.JTextField cxLinguagem;
    private javax.swing.JTextField cxNivel;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtEmail;
    private javax.swing.JLabel rtLinguagem;
    private javax.swing.JLabel rtNivel;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSalario;
    private javax.swing.JTable tbProg;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
