package View;
import model.Gerente;
import controller.GerenteCtrl;
import Exceptions.QtdEquipesInvException;
import java.util.List; // Import necessário
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadGerente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadGerente.class.getName());

    private GerenteCtrl controller;
    
    //MÉTODO SINGLETON --------------------------------
    private static FormCadGerente cpUnbic;

    private FormCadGerente() {
        initComponents();
        this.controller = new GerenteCtrl();
        listTab(); // Carrega a tabela com dados do banco ao iniciar
    }

    public static FormCadGerente geraCadGer() {
        if (cpUnbic == null) {
            cpUnbic = new FormCadGerente();
        }
        return cpUnbic;
    }
    //--------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify null code. The content of null method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimpar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        cxQtdEquipes = new javax.swing.JTextField();
        rtLinguagem = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        rtCpf = new javax.swing.JLabel();
        btConsGerCpf = new javax.swing.JButton();
        cxDepartamento = new javax.swing.JTextField();
        btInserirGer = new javax.swing.JButton();
        cxCpf = new javax.swing.JTextField();
        btAltGerCpf = new javax.swing.JButton();
        rtSalario = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        btExcGerCpf = new javax.swing.JButton();
        cxSalario = new javax.swing.JTextField();
        cxNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGer = new javax.swing.JTable();
        rtNivel1 = new javax.swing.JLabel();
        btCalcBonus = new javax.swing.JButton();
        cxCalcBonus = new javax.swing.JTextField();
        btGerarDescricao = new javax.swing.JButton();
        cxGerarDescricao = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        rtEmail = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Cadastro de Gerente");

        rtLinguagem.setText("DEPARTAMENTO:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtCpf.setText("CPF:");

        btConsGerCpf.setText("Consultar");
        btConsGerCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsGerCpfActionPerformed(evt);
            }
        });

        btInserirGer.setText("Inserir");
        btInserirGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirGerActionPerformed(evt);
            }
        });

        cxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfActionPerformed(evt);
            }
        });

        btAltGerCpf.setText("Alterar");
        btAltGerCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltGerCpfActionPerformed(evt);
            }
        });

        rtSalario.setText("SALARIO:");

        rtNome.setText("NOME:");

        btExcGerCpf.setText("Excluir");
        btExcGerCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcGerCpfActionPerformed(evt);
            }
        });

        tbGer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "SALARIO", "DEPARTAMENTO", "TIPO DE GERENCIA", "QTD EQUIPES "
            }
        ));
        tbGer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGer);

        rtNivel1.setText("QUANTIDADE DE EQUIPES GERENCIADAS:");

        btCalcBonus.setText("Calcular Bonus");
        btCalcBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcBonusActionPerformed(evt);
            }
        });

        btGerarDescricao.setText("Gerar Descricao");
        btGerarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDescricaoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Manual de Uso");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        rtEmail.setText("EMAIL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInserirGer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btConsGerCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAltGerCpf)
                                .addGap(18, 18, 18)
                                .addComponent(btExcGerCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCpf)
                                .addGap(18, 18, 18)
                                .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNivel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxQtdEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtLinguagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSalario)
                                .addGap(18, 18, 18)
                                .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxGerarDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btGerarDescricao)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cxCalcBonus, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btCalcBonus, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton1)
                                        .addGap(6, 6, 6)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCalcBonus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtCpf)
                            .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNome)
                            .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtSalario)
                            .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtEmail)
                            .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxCalcBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGerarDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxGerarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtLinguagem)
                            .addComponent(cxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNivel1)
                            .addComponent(cxQtdEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInserirGer)
                            .addComponent(btConsGerCpf)
                            .addComponent(btAltGerCpf)
                            .addComponent(btExcGerCpf))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btConsGerCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsGerCpfActionPerformed
        consGerCpf();
    }//GEN-LAST:event_btConsGerCpfActionPerformed

    private void btInserirGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirGerActionPerformed
        insGer();
        listTab();
    }//GEN-LAST:event_btInserirGerActionPerformed

    private void cxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfActionPerformed

    private void btAltGerCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltGerCpfActionPerformed

        altGerCpf();
        listTab();
    }//GEN-LAST:event_btAltGerCpfActionPerformed

    private void btExcGerCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcGerCpfActionPerformed
        excGerCpf();
        listTab();
    }//GEN-LAST:event_btExcGerCpfActionPerformed

    private void tbGerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGerMouseClicked

    }//GEN-LAST:event_tbGerMouseClicked

    private void btCalcBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcBonusActionPerformed
        calcBonusCpf();
    }//GEN-LAST:event_btCalcBonusActionPerformed

    private void btGerarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDescricaoActionPerformed
        gerarDescricaoCpf();
    }//GEN-LAST:event_btGerarDescricaoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        exibeManual();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void listTab() {
        DefaultTableModel modTab = (DefaultTableModel) tbGer.getModel();
        modTab.setRowCount(0); // Limpa a tabela

        List<Gerente> listaGerentes = controller.listaTodos();

        for (Gerente g : listaGerentes) {
            modTab.addRow(new Object[]{
                g.getCpf(),
                g.getNome(),
                g.getSalario(),
                g.getDepartamento(),
                g.getQtdEquipesGerenc()
            });
        }
    }

    public void excGerCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            int resp = JOptionPane.showConfirmDialog(
                null, 
                "Tem certeza que deseja excluir o gerente com CPF " + cpf + "?", 
                "Confirmação de Exclusão", 
                JOptionPane.YES_NO_OPTION
            );
            
            if (resp == JOptionPane.YES_OPTION) {
                controller.exclui(cpf);
                limpar();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O CPF deve ser um número inteiro!", "Erro de Exclusão", JOptionPane.ERROR_MESSAGE);
            cxCpf.requestFocus();
        }
    }

    public void altGerCpf() {
        try {
            Gerente g = new Gerente();
            g.setCpf(Integer.parseInt(cxCpf.getText()));
            g.setNome(cxNome.getText());
            g.setEmail(cxEmail.getText()); // Assumindo que cxEmail existe
            g.setSalario(Double.parseDouble(cxSalario.getText()));
            g.setDepartamento(cxDepartamento.getText());
            g.setQtdEquipesGerenc(Integer.parseInt(cxQtdEquipes.getText()));

            controller.atualiza(g);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "CPF, Salário e Qtd. de Equipes devem ser números válidos!", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (QtdEquipesInvException qeie) {
            JOptionPane.showMessageDialog(null, "A quantidade de equipes deve ser maior que zero.", "Dados Inválidos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void consGerCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            Gerente g = controller.buscaPorCpf(cpf);

            if (g != null) {
                cxCpf.setText(String.valueOf(g.getCpf()));
                cxNome.setText(g.getNome());
                cxEmail.setText(g.getEmail());
                cxSalario.setText(String.valueOf(g.getSalario()));
                cxDepartamento.setText(g.getDepartamento());
                cxQtdEquipes.setText(String.valueOf(g.getQtdEquipesGerenc()));
                JOptionPane.showMessageDialog(null, "Gerente encontrado!", "Consulta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado no banco de dados.", "Consulta", JOptionPane.WARNING_MESSAGE);
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O CPF deve ser um número inteiro!", "Erro de Consulta", JOptionPane.ERROR_MESSAGE);
            cxCpf.requestFocus();
        }
    }

    public void insGer() {
        Gerente gerente = new Gerente();
        try {
            // 1. Coleta os dados da tela
            gerente.setCpf(Integer.parseInt(cxCpf.getText()));
            gerente.setNome(cxNome.getText());
            gerente.setEmail(cxEmail.getText()); // Certifique-se que cxEmail existe no seu form
            gerente.setSalario(Double.parseDouble(cxSalario.getText()));
            gerente.setDepartamento(cxDepartamento.getText());
            // O setTipoGerencia foi removido do BD, então não precisamos mais dele aqui.
            // gerente.setTipoGerencia(cxTipo.getText());
            gerente.setQtdEquipesGerenc(Integer.parseInt(cxQtdEquipes.getText())); // Pode lançar QtdEquipesInvException

            // 2. Chama o controller da classe para tentar adicionar
            // As mensagens de sucesso (do Controller) ou erro de SQL (do ComandoSQL)
            // serão mostradas por eles.
            boolean sucesso = this.controller.adiciona(gerente);

            // 3. Limpa os campos e atualiza a tabela SOMENTE se a operação no banco deu certo
            if (sucesso) {
                limpar();
                listTab(); // Atualiza a tabela após inserção bem-sucedida
            }
            // Se 'sucesso' for false, o ComandoSQL já mostrou o erro (ex: CPF duplicado)
            // e não limpamos os campos para o usuário poder corrigir.

        } catch (NumberFormatException nfe) {
            // Erro de formato nos campos ANTES de ir para o banco
            JOptionPane.showMessageDialog(
                null,
                "CPF, Salário e Quantidade de Equipes devem ser números válidos!",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        } catch (QtdEquipesInvException qeie) {
            // Erro na validação da Qtd de Equipes ANTES de ir para o banco
            JOptionPane.showMessageDialog(
                null,
                "A quantidade de equipes gerenciadas deve ser maior que zero.",
                "Dados Inválidos",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        } catch (Exception e) {
            // Captura qualquer outro erro inesperado que possa ocorrer AQUI no formulário
            JOptionPane.showMessageDialog(
                null,
                "Ocorreu um erro inesperado no formulário: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        }
    }
    
    public void calcBonusCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            Gerente g = controller.buscaPorCpf(cpf);

            if (g != null) {
                cxCalcBonus.setText(String.format("%.2f", g.calcBonus()));
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado!", "Cálculo de Bônus", JOptionPane.WARNING_MESSAGE);
                cxCalcBonus.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Digite apenas números.", "Cálculo de Bônus", JOptionPane.ERROR_MESSAGE);
            cxCalcBonus.setText("");
            cxCpf.requestFocus();
        }
    }

    public void gerarDescricaoCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            Gerente g = controller.buscaPorCpf(cpf);

            if (g != null) {
                cxGerarDescricao.setText(g.gerarDescricaoCargo());
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado!", "Descrição de Cargo", JOptionPane.WARNING_MESSAGE);
                cxGerarDescricao.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Digite apenas números.", "Descrição de Cargo", JOptionPane.ERROR_MESSAGE);
            cxGerarDescricao.setText("");
            cxCpf.requestFocus();
        }
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    public void limpar() {
        cxCpf.setText("");
        cxNome.setText("");
        if (cxEmail != null) cxEmail.setText("");
        cxSalario.setText("");
        cxDepartamento.setText("");
        cxQtdEquipes.setText("");
        cxCalcBonus.setText("");
        cxGerarDescricao.setText("");
        cxCpf.requestFocus();
    }
    
    private void exibeManual() {
        String manual =
            "=== Manual de Uso do Sistema ===\n\n" +
            "1) Inserir:\n" +
            "   • Digite um CPF novo e os demais dados nas caixas de texto.\n" +
            "   • Clique em Inserir.\n\n" +
            "2) Consultar:\n" +
            "   • Digite um CPF já cadastrado.\n" +
            "   • Clique em Consultar.\n" +
            "   • Todos os dados daquele CPF aparecerão nas caixas de texto.\n\n" +
            "3) Alterar:\n" +
            "   • Digite um CPF já existente.\n" +
            "   • (Opcional) Clique em Consultar para carregar os dados atuais.\n" +
            "   • Edite os campos que desejar.\n" +
            "   • Clique em Alterar para sobrescrever o cadastro.\n\n" +
            "4) Excluir:\n" +
            "   • Digite um CPF existente.\n" +
            "   • Clique em Excluir.\n" +
            "   • Todos os dados desse cadastro serão removidos.\n\n" +
            "Extras:\n" +
            "   • Para calcular bônus ou gerar descrição, insira um CPF cadastrado\n" +
            "     e clique no botão correspondente.";

        JOptionPane.showMessageDialog(
            this,
            manual,
            "Ajuda / Manual do Sistema",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadGerente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltGerCpf;
    private javax.swing.JButton btCalcBonus;
    private javax.swing.JButton btConsGerCpf;
    private javax.swing.JButton btExcGerCpf;
    private javax.swing.JButton btGerarDescricao;
    private javax.swing.JButton btInserirGer;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCalcBonus;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxDepartamento;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxGerarDescricao;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxQtdEquipes;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtEmail;
    private javax.swing.JLabel rtLinguagem;
    private javax.swing.JLabel rtNivel1;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSalario;
    private javax.swing.JTable tbGer;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
