package View;

// --- Imports Adicionados ---
import controller.ProjetoCtrl; // Controller principal
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Projeto; // Modelo principal
import model.Funcionario; // Modelo para as tabelas de equipe
import model.Programador; // Modelo para a tabela de equipe
import model.AnalistaDeDados; // Modelo para a tabela de equipe
import javax.swing.JOptionPane; // Para mensagens de erro
import java.text.SimpleDateFormat; // Para formatar datas
/**
 *
 * @author augus
 */
public class FormConsProjeto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConsProjeto.class.getName());

    // --- Nossas Variáveis ---
    private ProjetoCtrl controller; // Controller de Projeto
    private DefaultTableModel modTblResultados; // Tabela de Projetos
    private DefaultTableModel modTblEquipeProg; // Tabela de Programadores
    private DefaultTableModel modTblEquipeAnalista; // Tabela de Analistas
    private static FormConsProjeto cpUnbic;
    // -----------------------

    /**
     * Creates new form FormConsGerente
     */
    public FormConsProjeto() {
        initComponents();
        
        // --- Nossa Inicialização ---
        this.controller = new ProjetoCtrl();
        this.modTblResultados = (DefaultTableModel) tblResultados.getModel();
        this.modTblEquipeProg = (DefaultTableModel) tblResultadosEquipeProg.getModel();
        this.modTblEquipeAnalista = (DefaultTableModel) tblResultadosEquipeAnalista.getModel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        carregarTabelaProjetos(); // Carrega a tabela principal
        // --------------------------
    }
    
    /**
     * Método Singleton
     */
    public static FormConsProjeto geraConsProj() { // Renomeado para ficar correto
        if (cpUnbic == null) {
            cpUnbic = new FormConsProjeto();
        }
        return cpUnbic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxNomeFiltro = new javax.swing.JTextField();
        cxStatusFiltro = new javax.swing.JTextField();
        cxGerenteResponsavelFiltro = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btListarTodos = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cxIdProjeto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResultadosEquipeProg = new javax.swing.JTable();
        btBuscarEquipe = new javax.swing.JButton();
        btListarTodos1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResultadosEquipeAnalista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cxGerenteResponsavelFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxGerenteResponsavelFiltroActionPerformed(evt);
            }
        });

        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btListarTodos.setText("LIMPAR");
        btListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarTodosActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Consulta de Projeto");

        jLabel2.setText("NOME:");

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "STATUS", "DATA INICIAL", "PRAZO FINAL", "GERENTE RESPONSAVEL"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        jLabel3.setText("STATUS:");

        jLabel4.setText("GERENTE RESPONSAVEL:");

        jLabel5.setText("ID:");

        tblResultadosEquipeProg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "PROGRAMADORES"
            }
        ));
        jScrollPane2.setViewportView(tblResultadosEquipeProg);

        btBuscarEquipe.setText("BUSCAR");
        btBuscarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarEquipeActionPerformed(evt);
            }
        });

        btListarTodos1.setText("LIMPAR");
        btListarTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarTodos1ActionPerformed(evt);
            }
        });

        tblResultadosEquipeAnalista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ANALISTAS DE DADOS"
            }
        ));
        jScrollPane3.setViewportView(tblResultadosEquipeAnalista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTitulo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cxNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cxStatusFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cxGerenteResponsavelFiltro))
                            .addGap(32, 32, 32)
                            .addComponent(btBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(btListarTodos)
                            .addGap(12, 12, 12)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxIdProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btListarTodos1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cxStatusFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btBuscar)
                                .addComponent(btListarTodos))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxGerenteResponsavelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxIdProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarEquipe)
                            .addComponent(btListarTodos1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // 1. Coleta os filtros da tabela principal
        String nome = cxNomeFiltro.getText();
        String status = cxStatusFiltro.getText();
        String gerenteNome = cxGerenteResponsavelFiltro.getText(); // <-- 1. Variável renomeada

        // 2. Chama o controller de Projeto para buscar com os filtros
        List<Projeto> listaFiltrada = controller.buscarPorFiltros(nome, status, gerenteNome); // <-- 2. Chamada atualizada

        // 3. Preenche a tabela de PROJETOS com os resultados
        preencherTabelaProjetos(listaFiltrada);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarTodosActionPerformed
        // 1. Limpa os campos de filtro
        cxNomeFiltro.setText("");
        cxStatusFiltro.setText("");
        cxGerenteResponsavelFiltro.setText("");

        // 2. Carrega a tabela de PROJETOS com a lista completa
        carregarTabelaProjetos();
    }//GEN-LAST:event_btListarTodosActionPerformed

    private void btBuscarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarEquipeActionPerformed
        try {
            // 1. Pega o ID do projeto digitado
            int idProjeto = Integer.parseInt(cxIdProjeto.getText());
            
            // 2. Busca os Programadores e Analistas para esse ID
            // Chama o controller de Projeto para buscar os membros
            List<Funcionario> programadores = controller.listarMembrosPorCargo(idProjeto, "Programador");
            List<Funcionario> analistas = controller.listarMembrosPorCargo(idProjeto, "AnalistaDeDados");
            
            // 3. Preenche as tabelas de equipe
            preencherTabelaProgramadores(programadores);
            preencherTabelaAnalistas(analistas);
            
            if (programadores.isEmpty() && analistas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum membro (programador ou analista) encontrado para o Projeto ID " + idProjeto, "Busca de Equipe", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O ID do Projeto deve ser um número.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarEquipeActionPerformed

    private void btListarTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarTodos1ActionPerformed
        // Limpa o campo de ID e as duas tabelas de equipe
        cxIdProjeto.setText("");
        modTblEquipeProg.setRowCount(0);
        modTblEquipeAnalista.setRowCount(0);
    }//GEN-LAST:event_btListarTodos1ActionPerformed

    private void cxGerenteResponsavelFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxGerenteResponsavelFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxGerenteResponsavelFiltroActionPerformed

    private void carregarTabelaProjetos() {
        List<Projeto> listaCompleta = controller.listaTodos();
        preencherTabelaProjetos(listaCompleta);
    }
    private void preencherTabelaProjetos(List<Projeto> lista) {
        modTblResultados.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Projeto p : lista) {
            String nomeGerente = (p.getGerenteResponsavel() != null) ? p.getGerenteResponsavel().getNome() : "N/D";
            String dataInicio = (p.getDataInicio() != null) ? sdf.format(p.getDataInicio()) : "N/D";
            String prazoFinal = (p.getPrazoFinal() != null) ? sdf.format(p.getPrazoFinal()) : "N/D";
            
            modTblResultados.addRow(new Object[]{
                p.getIdProjeto(),
                p.getNomeProjeto(),
                p.getStatus(),
                dataInicio,
                prazoFinal,
                nomeGerente
            });
        }
    }
    private void preencherTabelaProgramadores(List<Funcionario> lista) {
        modTblEquipeProg.setRowCount(0);
        for (Funcionario f : lista) {
            if (f instanceof Programador) {
                Programador p = (Programador) f;
                // Mostra nome e CPF para diferenciar
                modTblEquipeProg.addRow(new Object[]{
                    p.getNome() + " (CPF: " + p.getCpf() + ")"
                });
            }
        }
    }
    private void preencherTabelaAnalistas(List<Funcionario> lista) {
        modTblEquipeAnalista.setRowCount(0);
        for (Funcionario f : lista) {
            if (f instanceof AnalistaDeDados) {
                AnalistaDeDados a = (AnalistaDeDados) f;
                modTblEquipeAnalista.addRow(new Object[]{
                    a.getNome() + " (CPF: " + a.getCpf() + ")"
                });
            }
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConsProjeto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscarEquipe;
    private javax.swing.JButton btListarTodos;
    private javax.swing.JButton btListarTodos1;
    private javax.swing.JTextField cxGerenteResponsavelFiltro;
    private javax.swing.JTextField cxIdProjeto;
    private javax.swing.JTextField cxNomeFiltro;
    private javax.swing.JTextField cxStatusFiltro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTable tblResultadosEquipeAnalista;
    private javax.swing.JTable tblResultadosEquipeProg;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
