//Augusto da Silva de Sá - RA: 2564319
package View;
import model.AnalistaDeDados;
import controller.AnalistaDeDadosCtrl;
import java.util.List; // Import necessário
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadAnalista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadAnalista.class.getName());
       
    //INSTANCIACAO-----------------------------------
    
    private AnalistaDeDadosCtrl controller;
    
        //SINGLETON
    private static FormCadAnalista cpUnbic;

    private FormCadAnalista() {
        initComponents();
        this.controller = new AnalistaDeDadosCtrl();
        listTab(); // Carrega a tabela com dados do banco ao iniciar
    }

    public static FormCadAnalista geraCadAna() {
        if (cpUnbic == null) {
            cpUnbic = new FormCadAnalista();
        }
        return cpUnbic;
    }
    //-------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btConsAnaCpf = new javax.swing.JButton();
        btInserirAna = new javax.swing.JButton();
        cxRelatorios = new javax.swing.JTextField();
        btAltAnaCpf = new javax.swing.JButton();
        btExcAnaCpf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAna = new javax.swing.JTable();
        rtSalario = new javax.swing.JLabel();
        cxSalario = new javax.swing.JTextField();
        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        rtFerramentas = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        cxFerramentas = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        rtRelatorios = new javax.swing.JLabel();
        btCalcBonus = new javax.swing.JButton();
        cxCalcBonus = new javax.swing.JTextField();
        btGerarDescricao = new javax.swing.JButton();
        cxGerarDescricao = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        rtEmail = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btConsAnaCpf.setText("Consultar");
        btConsAnaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsAnaCpfActionPerformed(evt);
            }
        });

        btInserirAna.setText("Inserir");
        btInserirAna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirAnaActionPerformed(evt);
            }
        });

        btAltAnaCpf.setText("Alterar");
        btAltAnaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltAnaCpfActionPerformed(evt);
            }
        });

        btExcAnaCpf.setText("Excluir");
        btExcAnaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcAnaCpfActionPerformed(evt);
            }
        });

        tbAna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "SALARIO", "FERRAMENTAS", "QTD DE RELATÓRIOS"
            }
        ));
        tbAna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAnaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAna);

        rtSalario.setText("SALARIO:");

        rtCpf.setText("CPF:");

        cxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Cadastro de Analista de Dados");

        rtNome.setText("NOME:");

        rtFerramentas.setText("FERRAMENTA(S):");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtRelatorios.setText("QUANTIDADE DE RELATÓRIOS:");

        btCalcBonus.setText("Calcular Bonus");
        btCalcBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcBonusActionPerformed(evt);
            }
        });

        btGerarDescricao.setText("Gerar Descricao");
        btGerarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDescricaoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Manual de Uso");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        rtEmail.setText("EMAIL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSalario)
                                .addGap(18, 18, 18)
                                .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rtCpf)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxCpf))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtFerramentas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rtRelatorios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cxRelatorios))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btInserirAna)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btConsAnaCpf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btAltAnaCpf)))
                                .addGap(18, 18, 18)
                                .addComponent(btExcAnaCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btGerarDescricao)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cxCalcBonus, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCalcBonus, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(cxGerarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(171, 171, 171)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtCpf)
                            .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNome)
                            .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btCalcBonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCalcBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGerarDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxGerarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtEmail)
                            .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtSalario)
                            .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtFerramentas)
                            .addComponent(cxFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtRelatorios)
                            .addComponent(cxRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInserirAna)
                            .addComponent(btConsAnaCpf)
                            .addComponent(btAltAnaCpf)
                            .addComponent(btExcAnaCpf))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsAnaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsAnaCpfActionPerformed
        consAnaCpf();
    }//GEN-LAST:event_btConsAnaCpfActionPerformed

    private void btInserirAnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirAnaActionPerformed
        insAna();
        listTab();
    }//GEN-LAST:event_btInserirAnaActionPerformed

    private void btAltAnaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltAnaCpfActionPerformed

        altAnaCpf();
        listTab();
    }//GEN-LAST:event_btAltAnaCpfActionPerformed

    private void btExcAnaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcAnaCpfActionPerformed
        excAnaCpf();
        listTab();
    }//GEN-LAST:event_btExcAnaCpfActionPerformed

    private void tbAnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAnaMouseClicked

    }//GEN-LAST:event_tbAnaMouseClicked

    private void cxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCalcBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcBonusActionPerformed
        calcBonusCpf();
    }//GEN-LAST:event_btCalcBonusActionPerformed

    private void btGerarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDescricaoActionPerformed
        gerarDescricaoCpf();
    }//GEN-LAST:event_btGerarDescricaoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        exibeManual();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void listTab() {
        DefaultTableModel modTab = (DefaultTableModel) tbAna.getModel();
        modTab.setRowCount(0); // Limpa a tabela

        List<AnalistaDeDados> listaAnalistas = controller.listaTodos();

        for (AnalistaDeDados a : listaAnalistas) {
            modTab.addRow(new Object[]{
                a.getCpf(),
                a.getNome(),
                a.getSalario(),
                a.getFerramenta(),
                a.getQtdRelatorios()
            });
        }
    }

    public void excAnaCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            int resp = JOptionPane.showConfirmDialog(
                null, 
                "Tem certeza que deseja excluir o analista com CPF " + cpf + "?", 
                "Confirmação de Exclusão", 
                JOptionPane.YES_NO_OPTION
            );
            
            if (resp == JOptionPane.YES_OPTION) {
                controller.exclui(cpf);
                limpar();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O CPF deve ser um número inteiro!", "Erro de Exclusão", JOptionPane.ERROR_MESSAGE);
            cxCpf.requestFocus();
        }
    }

    public void altAnaCpf() {
        try {
            AnalistaDeDados a = new AnalistaDeDados();
            a.setCpf(Integer.parseInt(cxCpf.getText()));
            a.setNome(cxNome.getText());
            a.setEmail(cxEmail.getText());
            a.setSalario(Double.parseDouble(cxSalario.getText()));
            a.setFerramenta(cxFerramentas.getText());
            a.setQtdRelatorios(Integer.parseInt(cxRelatorios.getText()));

            controller.atualiza(a);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "CPF, Salário e Qtd. de Relatórios devem ser números válidos!", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void consAnaCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            AnalistaDeDados a = controller.buscaPorCpf(cpf);

            if (a != null) {
                cxCpf.setText(String.valueOf(a.getCpf()));
                cxNome.setText(a.getNome());
                cxEmail.setText(a.getEmail());
                cxSalario.setText(String.valueOf(a.getSalario()));
                cxFerramentas.setText(a.getFerramenta());
                cxRelatorios.setText(String.valueOf(a.getQtdRelatorios()));
                JOptionPane.showMessageDialog(null, "Analista encontrado!", "Consulta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado no banco de dados.", "Consulta", JOptionPane.WARNING_MESSAGE);
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O CPF deve ser um número inteiro!", "Erro de Consulta", JOptionPane.ERROR_MESSAGE);
            cxCpf.requestFocus();
        }
    }

    public void insAna() {
        AnalistaDeDados analista = new AnalistaDeDados();
        try {
            // 1. Coleta os dados da tela
            analista.setCpf(Integer.parseInt(cxCpf.getText()));
            analista.setNome(cxNome.getText());
            analista.setEmail(cxEmail.getText()); // Certifique-se que cxEmail existe no seu form
            analista.setSalario(Double.parseDouble(cxSalario.getText()));
            analista.setFerramenta(cxFerramentas.getText());
            analista.setQtdRelatorios(Integer.parseInt(cxRelatorios.getText()));

            // 2. Chama o controller da classe para tentar adicionar
            // As mensagens de sucesso (do Controller) ou erro de SQL (do ComandoSQL)
            // serão mostradas por eles.
            boolean sucesso = this.controller.adiciona(analista);

            // 3. Limpa os campos e atualiza a tabela SOMENTE se a operação no banco deu certo
            if (sucesso) {
                limpar();
                listTab(); // Atualiza a tabela após inserção bem-sucedida
            }
            // Se 'sucesso' for false, o ComandoSQL já mostrou o erro (ex: CPF duplicado)
            // e não limpamos os campos para o usuário poder corrigir.

        } catch (NumberFormatException nfe) {
            // Erro de formato nos campos ANTES de ir para o banco
            JOptionPane.showMessageDialog(
                null,
                "CPF, Salário e Quantidade de Relatórios devem ser números válidos!",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        } catch (Exception e) {
            // Captura qualquer outro erro inesperado que possa ocorrer AQUI no formulário
            // (Pode incluir erros de validação da classe AnalistaDeDados, se houver)
            JOptionPane.showMessageDialog(
                null,
                "Ocorreu um erro inesperado no formulário: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            // Não limpa
        }
    }
    
    public void calcBonusCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            AnalistaDeDados a = controller.buscaPorCpf(cpf);

            if (a != null) {
                cxCalcBonus.setText(String.format("%.2f", a.calcBonus()));
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado!", "Cálculo de Bônus", JOptionPane.WARNING_MESSAGE);
                cxCalcBonus.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Digite apenas números.", "Cálculo de Bônus", JOptionPane.ERROR_MESSAGE);
            cxCalcBonus.setText("");
            cxCpf.requestFocus();
        }
    }

    public void gerarDescricaoCpf() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText());
            AnalistaDeDados a = controller.buscaPorCpf(cpf);

            if (a != null) {
                cxGerarDescricao.setText(a.gerarDescricaoCargo());
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado!", "Descrição de Cargo", JOptionPane.WARNING_MESSAGE);
                cxGerarDescricao.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Digite apenas números.", "Descrição de Cargo", JOptionPane.ERROR_MESSAGE);
            cxGerarDescricao.setText("");
            cxCpf.requestFocus();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           //System.exit(0);
           dispose();
       }
    }
    
    public void limpar() {
        cxCpf.setText("");
        cxNome.setText("");
        cxEmail.setText("");
        cxSalario.setText("");
        cxFerramentas.setText("");
        cxRelatorios.setText("");
        cxCalcBonus.setText("");
        cxGerarDescricao.setText("");
        cxCpf.requestFocus();
    }
    
    private void exibeManual() {
        String manual =
            "=== Manual de Uso do Sistema ===\n\n" +
            "1) Inserir:\n" +
            "   • Digite um CPF novo e os demais dados nas caixas de texto.\n" +
            "   • Clique em Inserir.\n\n" +
            "2) Consultar:\n" +
            "   • Digite um CPF já cadastrado.\n" +
            "   • Clique em Consultar.\n" +
            "   • Todos os dados daquele CPF aparecerão nas caixas de texto.\n\n" +
            "3) Alterar:\n" +
            "   • Digite um CPF já existente.\n" +
            "   • (Opcional) Clique em Consultar para carregar os dados atuais.\n" +
            "   • Edite os campos que desejar.\n" +
            "   • Clique em Alterar para sobrescrever o cadastro.\n\n" +
            "4) Excluir:\n" +
            "   • Digite um CPF existente.\n" +
            "   • Clique em Excluir.\n" +
            "   • Todos os dados desse cadastro serão removidos.\n\n" +
            "Extras:\n" +
            "   • Para calcular bônus ou gerar descrição, insira um CPF cadastrado\n" +
            "     e clique no botão correspondente.";

        JOptionPane.showMessageDialog(
            this,
            manual,
            "Ajuda / Manual do Sistema",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadAnalista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltAnaCpf;
    private javax.swing.JButton btCalcBonus;
    private javax.swing.JButton btConsAnaCpf;
    private javax.swing.JButton btExcAnaCpf;
    private javax.swing.JButton btGerarDescricao;
    private javax.swing.JButton btInserirAna;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCalcBonus;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxFerramentas;
    private javax.swing.JTextField cxGerarDescricao;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxRelatorios;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtEmail;
    private javax.swing.JLabel rtFerramentas;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtRelatorios;
    private javax.swing.JLabel rtSalario;
    private javax.swing.JTable tbAna;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
