package View;

import controller.GerenteCtrl;
import controller.ProjetoCtrl;
import controller.AnalistaDeDadosCtrl; // Import necessário
import controller.ProgramadorCtrl;    // Import necessário
import model.Gerente;
import model.Projeto;
import model.Funcionario;
import model.Programador;      // Import necessário
import model.AnalistaDeDados;  // Import necessário

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList; // Import necessário
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author augus
 */
public class FormCadProjeto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadProjeto.class.getName());
    // --- Controllers ---
    private ProjetoCtrl projetoController;
    private GerenteCtrl gerenteController;
    private ProgramadorCtrl programadorController;
    private AnalistaDeDadosCtrl analistaController;

    // --- Modelos dos Componentes ---
    private DefaultComboBoxModel<Gerente> modCmbGerente;
    private DefaultComboBoxModel<Programador> modCmbProgramadores;
    private DefaultComboBoxModel<AnalistaDeDados> modCmbAnalistas;
    private DefaultComboBoxModel<String> modCmbStatus;
    private DefaultTableModel modTblProjetos;
    
    // --- "Memória" da Equipe ---
    // Lista para "preparar" a equipe antes de salvar
    private List<Funcionario> equipeStaged;

    private static FormCadProjeto cpUnbic;

    public FormCadProjeto() {
        initComponents();

        // Inicializa os controllers
        this.projetoController = new ProjetoCtrl();
        this.gerenteController = new GerenteCtrl();
        this.programadorController = new ProgramadorCtrl();
        this.analistaController = new AnalistaDeDadosCtrl();
        
        // Inicializa a lista da equipe
        this.equipeStaged = new ArrayList<>();

        configurarModelos();
        carregarComboBoxes();
        
        // Vamos desabilitar os botões de adicionar equipe até que um projeto seja criado/selecionado
        // (Isso será para a próxima etapa, por enquanto vamos focar na inserção)
    }

    public static FormCadProjeto geraCadProj() {
        if (cpUnbic == null) {
            cpUnbic = new FormCadProjeto();
        }
        return cpUnbic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rtLinguagem = new javax.swing.JLabel();
        cxNomeProjeto = new javax.swing.JTextField();
        rtNivel = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        rtEmail = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        rtSalario = new javax.swing.JLabel();
        cxDataInicio = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        cxPrazoFinal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjetos = new javax.swing.JTable();
        txtTitulo = new javax.swing.JLabel();
        cxIdProjeto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbGerente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbProgramadores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbAnalistas = new javax.swing.JComboBox<>();
        btAddProgramador = new javax.swing.JButton();
        btAddAnalista = new javax.swing.JButton();
        btExcluirProgramador = new javax.swing.JButton();
        btExcluirAnalista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rtLinguagem.setText("PRAZO FINAL:");

        cxNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeProjetoActionPerformed(evt);
            }
        });

        rtNivel.setText("GERENTE RESPONSÁVEL:");

        rtNome.setText("NOME DO PROJETO:");

        btInserir.setText("Criar Projeto");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        rtEmail.setText("STATUS:");

        btAlterar.setText("Alterar Projeto");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        rtSalario.setText("DATA INICIAL:");

        cxDataInicio.setText("dd/mm/aaaa");
        cxDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDataInicioActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Projeto");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tblProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "STATUS", "Gerente Responsável"
            }
        ));
        tblProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjetosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProjetos);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setText("Cadastro de Projeto");

        cxIdProjeto.setEditable(false);

        jLabel1.setText("ID");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGerenteActionPerformed(evt);
            }
        });

        jLabel2.setText("PROGRAMADORES");

        jLabel3.setText("ANALISTAS");

        btAddProgramador.setText("Adicionar Programador");
        btAddProgramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProgramadorActionPerformed(evt);
            }
        });

        btAddAnalista.setText("Adicionar Analista");
        btAddAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAnalistaActionPerformed(evt);
            }
        });

        btExcluirProgramador.setText("Exclui Programador");
        btExcluirProgramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirProgramadorActionPerformed(evt);
            }
        });

        btExcluirAnalista.setText("Exclui Analista");
        btExcluirAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirAnalistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cxIdProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(txtTitulo)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtEmail)
                                        .addGap(30, 30, 30)
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rtSalario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rtNivel)
                                    .addComponent(cmbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtLinguagem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxPrazoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(cmbProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(cmbAnalistas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btAddProgramador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btExcluirProgramador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btAddAnalista)
                                            .addComponent(btExcluirAnalista))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxIdProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEmail)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtSalario)
                    .addComponent(rtLinguagem)
                    .addComponent(cxPrazoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnalistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddProgramador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluirProgramador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddAnalista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluirAnalista)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeProjetoActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        criarNovoProjeto();
    }//GEN-LAST:event_btInserirActionPerformed

    private void tblProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjetosMouseClicked

    }//GEN-LAST:event_tblProjetosMouseClicked

    private void cmbGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGerenteActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed


    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAddProgramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProgramadorActionPerformed
        Programador p = (Programador) cmbProgramadores.getSelectedItem();
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Selecione um programador na lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verifica se ele já foi adicionado
        for (Funcionario f : equipeStaged) {
            if (f.getCpf() == p.getCpf()) {
                JOptionPane.showMessageDialog(this, "Erro: Programador '" + p.getNome() + "' já está na equipe.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Adiciona à lista
        equipeStaged.add(p);
        JOptionPane.showMessageDialog(this, "Programador '" + p.getNome() + "' adicionado à equipe.\nTotal na equipe: " + equipeStaged.size(), "Sucesso", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btAddProgramadorActionPerformed

    private void btAddAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAnalistaActionPerformed
        AnalistaDeDados a = (AnalistaDeDados) cmbAnalistas.getSelectedItem();
        if (a == null) {
            JOptionPane.showMessageDialog(this, "Selecione um analista na lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verifica se ele já foi adicionado
        for (Funcionario f : equipeStaged) {
            if (f.getCpf() == a.getCpf()) {
                JOptionPane.showMessageDialog(this, "Erro: Analista '" + a.getNome() + "' já está na equipe.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Adiciona à lista
        equipeStaged.add(a);
        JOptionPane.showMessageDialog(this, "Analista '" + a.getNome() + "' adicionado à equipe.\nTotal na equipe: " + equipeStaged.size(), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btAddAnalistaActionPerformed

    private void cxDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataInicioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listTab();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btExcluirProgramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirProgramadorActionPerformed
        // Pega o programador selecionado no ComboBox
        Programador pSelecionado = (Programador) cmbProgramadores.getSelectedItem();

        // Verifica se realmente tem um programador selecionado
        if (pSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um programador na lista para remover.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tenta remover o programador da lista 'equipeStaged'
        boolean removido = false;
        for (int i = 0; i < equipeStaged.size(); i++) {
            // Compara pelo CPF para garantir que é o mesmo funcionário
            if (equipeStaged.get(i).getCpf() == pSelecionado.getCpf()) {
                equipeStaged.remove(i);
                removido = true;
                break; // Sai do loop assim que remover
            }
        }

        // Exibe a mensagem de acordo com o resultado
        if (removido) {
            // Se você adicionar a JList da equipe depois, atualize-a aqui também: modLstEquipe.removeElement(pSelecionado);
            JOptionPane.showMessageDialog(this, "'" + pSelecionado.getNome() + "' removido da equipe.\nTotal: "
                    + equipeStaged.size() + " membro(s) (sem contar o gerente).",
                    "Equipe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "O programador '" + pSelecionado.getNome() + "' não estava na equipe atual.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btExcluirProgramadorActionPerformed

    private void btExcluirAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirAnalistaActionPerformed
        // Pega o analista selecionado no ComboBox
        AnalistaDeDados aSelecionado = (AnalistaDeDados) cmbAnalistas.getSelectedItem();

        // Verifica se realmente tem um analista selecionado
        if (aSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um analista na lista para remover.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tenta remover o analista da lista 'equipeStaged'
        boolean removido = false;
        for (int i = 0; i < equipeStaged.size(); i++) {
            if (equipeStaged.get(i).getCpf() == aSelecionado.getCpf()) {
                equipeStaged.remove(i);
                removido = true;
                break;
            }
        }

        // Exibe a mensagem
        if (removido) {
            // Atualizar JList da equipe aqui, se existir: modLstEquipe.removeElement(aSelecionado);
            JOptionPane.showMessageDialog(this, "'" + aSelecionado.getNome() + "' removido da equipe.\nTotal: "
                    + equipeStaged.size() + " membro(s) (sem contar o gerente).",
                    "Equipe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "O analista '" + aSelecionado.getNome() + "' não estava na equipe atual.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirAnalistaActionPerformed
    
    private void criarNovoProjeto() {
        // ---- ETAPA 1: VALIDAÇÃO DAS REGRAS ----

        // Regra 1: Valida Gerente
        Gerente gerenteSelecionado = (Gerente) cmbGerente.getSelectedItem();
        if (gerenteSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Erro: Selecione um Gerente responsável.", "Validação Falhou", JOptionPane.ERROR_MESSAGE);
            return; // PARA A EXECUÇÃO
        }

        // Regra 2: Valida Equipe Mínima (Gerente + 2 outros)
        if (equipeStaged.size() < 2) {
            JOptionPane.showMessageDialog(this, "Erro: A equipe deve ter o Gerente e pelo menos mais 2 funcionários (programadores/analistas).", "Validação Falhou", JOptionPane.ERROR_MESSAGE);
            return; // PARA A EXECUÇÃO
        }

        // Regra 3: Valida Datas
        Date dataInicio = null; // Inicializa como null
        String dataInicioStr = cxDataInicio.getText().trim();

        if (dataInicioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro: A Data de Início é obrigatória.", "Validação Falhou", JOptionPane.ERROR_MESSAGE);
            return; // PARA A EXECUÇÃO
        } else {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                sdf.setLenient(false); // Garante que a data seja válida
                dataInicio = sdf.parse(dataInicioStr); // Tenta converter
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this,
                        "Data de Início inválida!\n- Use o formato dd/mm/aaaa.\n- Certifique-se que o dia e mês são válidos.",
                        "Erro de Data", JOptionPane.ERROR_MESSAGE);
                return; // PARA A EXECUÇÃO se o formato ou a data for inválida
            }
        }

        // Validação Prazo Final (Opcional)
        Date prazoFinal = null; // Inicializa como null
        String prazoFinalStr = cxPrazoFinal.getText().trim();

        if (!prazoFinalStr.isEmpty()) { // Só tenta converter se não estiver vazio
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                sdf.setLenient(false);
                prazoFinal = sdf.parse(prazoFinalStr);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this,
                        "Prazo Final inválido!\n- Use o formato dd/mm/aaaa.\n- Certifique-se que o dia e mês são válidos.",
                        "Erro de Data", JOptionPane.ERROR_MESSAGE);
                return; // PARA A EXECUÇÃO se o formato ou data for inválida
            }
        }

        // Validação Lógica: Prazo Final antes do Início
        if (prazoFinal != null && prazoFinal.before(dataInicio)) {
            JOptionPane.showMessageDialog(this, "Erro: O Prazo Final não pode ser anterior à Data de Início.", "Validação Falhou", JOptionPane.ERROR_MESSAGE);
            return; // PARA A EXECUÇÃO
        }

        // Validação Lógica: Prazo Final antes do Início
        if (prazoFinal != null && prazoFinal.before(dataInicio)) {
            JOptionPane.showMessageDialog(this, "Erro: O Prazo Final não pode ser anterior à Data de Início.", "Validação Falhou", JOptionPane.ERROR_MESSAGE);
            return; // PARA A EXECUÇÃO
        }

        // ---- ETAPA 2: CRIAÇÃO DO PROJETO E SALVAR ----
        try {
            Projeto novoProjeto = new Projeto();
            novoProjeto.setNomeProjeto(cxNomeProjeto.getText());
            novoProjeto.setStatus(cmbStatus.getSelectedItem().toString());
            novoProjeto.setGerenteResponsavel(gerenteSelecionado);
            novoProjeto.setDataInicio(dataInicio); // Já validada
            novoProjeto.setPrazoFinal(prazoFinal); // Pode ser null

            // Salvar Projeto e pegar ID
            int novoIdProjeto = projetoController.adicionaEretornaId(novoProjeto);
            if (novoIdProjeto == -1) {
                // A mensagem de erro específica do SQL já foi mostrada pelo controller/ComandoSQL
                JOptionPane.showMessageDialog(this, "Não foi possível criar o projeto. Verifique os dados e tente novamente.", "Erro ao Salvar", JOptionPane.ERROR_MESSAGE);
                return; // PARA A EXECUÇÃO
            }

            // Salvar Equipe no BD
            projetoController.adicionarMembroEquipe(novoIdProjeto, gerenteSelecionado.getCpf());
            for (Funcionario f : equipeStaged) {
                projetoController.adicionarMembroEquipe(novoIdProjeto, f.getCpf());
            }

            // Mensagem ÚNICA de sucesso
            JOptionPane.showMessageDialog(this, "Projeto ID " + novoIdProjeto + " criado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            limparFormulario(); // Limpa tudo após o sucesso
            listTab(); // Atualiza a tabela de projetos

        } catch (Exception e) {
            // Captura qualquer outro erro inesperado durante o processo
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprime o erro detalhado no console para debug
        }
    }
    
    private void configurarModelos() {
        // Configura a tabela de projetos
        modTblProjetos = (DefaultTableModel) tblProjetos.getModel();
        modTblProjetos.setColumnIdentifiers(new Object[]{"ID", "Nome", "Status", "Gerente"});
        modTblProjetos.setRowCount(0);

        // Configura os ComboBoxes de Funcionários
        modCmbGerente = new DefaultComboBoxModel<>();
        cmbGerente.setModel(modCmbGerente);
        
        modCmbProgramadores = new DefaultComboBoxModel<>();
        cmbProgramadores.setModel(modCmbProgramadores);
        
        modCmbAnalistas = new DefaultComboBoxModel<>();
        cmbAnalistas.setModel(modCmbAnalistas);
        
        // Configura o ComboBox de Status
        modCmbStatus = new DefaultComboBoxModel<>(new String[] {
            "Planejamento", "Em Andamento", "Concluído", "Pausado", "Cancelado"
        });
        cmbStatus.setModel(modCmbStatus);
    }
    
    private void carregarComboBoxes() {
        // Carrega Gerentes
        modCmbGerente.removeAllElements();
        modCmbGerente.addElement(null); // Opção para "Nenhum"
        List<Gerente> gerentes = gerenteController.listaTodos();
        for (Gerente g : gerentes) {
            modCmbGerente.addElement(g);
        }
        
        // Carrega Programadores
        modCmbProgramadores.removeAllElements();
        modCmbProgramadores.addElement(null);
        List<Programador> programadores = programadorController.listaTodos();
        for (Programador p : programadores) {
            modCmbProgramadores.addElement(p);
        }
        
        // Carrega Analistas
        modCmbAnalistas.removeAllElements();
        modCmbAnalistas.addElement(null);
        List<AnalistaDeDados> analistas = analistaController.listaTodos();
        for (AnalistaDeDados a : analistas) {
            modCmbAnalistas.addElement(a);
        }
    }
    
    private Date parseDate(String data) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(data);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida. Use o formato dd/mm/aaaa.", "Erro de Data", JOptionPane.ERROR_MESSAGE);
            return null; // Retorna nulo se a data for inválida
        }
    }
    
    // Substitua o método listTab() existente por este
    private void listTab() {
        // Pega o modelo da tabela que você criou no NetBeans
        DefaultTableModel modTab = (DefaultTableModel) tblProjetos.getModel();
        modTab.setRowCount(0); // Limpa as linhas existentes da tabela

        // Pede ao controller a lista de todos os projetos do banco
        // (Este método listaTodos() já deve estar funcional no ProjetoCtrl)
        List<Projeto> listaProjetos = projetoController.listaTodos();

        // Loop para percorrer cada projeto na lista retornada
        for (Projeto p : listaProjetos) {
            // Prepara os dados para a linha da tabela
            
            // Pega o nome do gerente (ou "N/D" se não houver gerente)
            String nomeGerente = "N/D"; // Valor padrão
            if (p.getGerenteResponsavel() != null) {
                nomeGerente = p.getGerenteResponsavel().getNome();
            }
            
            // Adiciona uma nova linha na tabela com os dados do projeto
            modTab.addRow(new Object[]{
                p.getIdProjeto(),       // Coluna 0: ID
                p.getNomeProjeto(),     // Coluna 1: Nome
                p.getStatus(),          // Coluna 2: Status
                nomeGerente             // Coluna 3: Gerente Responsável (Nome)
            });
        }
    }
    
    private void limparFormulario() {
        cxIdProjeto.setText("");
        cxNomeProjeto.setText("");
        cmbStatus.setSelectedIndex(0);
        cxDataInicio.setText("");
        cxPrazoFinal.setText("");
        cmbGerente.setSelectedItem(null);
        cmbProgramadores.setSelectedItem(null);
        cmbAnalistas.setSelectedItem(null);
        
        // Limpa a equipe que estava sendo preparada
        equipeStaged.clear();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadProjeto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAnalista;
    private javax.swing.JButton btAddProgramador;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluirAnalista;
    private javax.swing.JButton btExcluirProgramador;
    private javax.swing.JButton btInserir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<AnalistaDeDados> cmbAnalistas;
    private javax.swing.JComboBox<Gerente> cmbGerente;
    private javax.swing.JComboBox<Programador> cmbProgramadores;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JTextField cxDataInicio;
    private javax.swing.JTextField cxIdProjeto;
    private javax.swing.JTextField cxNomeProjeto;
    private javax.swing.JTextField cxPrazoFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtEmail;
    private javax.swing.JLabel rtLinguagem;
    private javax.swing.JLabel rtNivel;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSalario;
    private javax.swing.JTable tblProjetos;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
